// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hefzniswapqvycekxoze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZnpuaXN3YXBxdnljZWt4b3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDQxMTYsImV4cCI6MjA2NjY4MDExNn0.Sl-SfVq8JQ8ENY-wcDr8HSJhDF13SaJoZ1PFKE18ipE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);